# Generated by Django 5.0 on 2023-12-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
