# Generated by Django 5.0 on 2023-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_diary', '0002_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='is_allday',
            field=models.BooleanField(default=True),
        ),
    ]
